/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Crops */
        get: operations["list_crops_crops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farm-crops/{farm_crop_id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Activity */
        post: operations["create_activity_farm_crops__farm_crop_id__activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Farms */
        get: operations["list_farms_farms_get"];
        put?: never;
        /** Create Farm */
        post: operations["create_farm_farms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Farm */
        get: operations["get_farm_farms__farm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Farm */
        patch: operations["update_farm_farms__farm_id__patch"];
        trace?: never;
    };
    "/farms/{farm_id}/advisories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Advisories */
        get: operations["list_advisories_farms__farm_id__advisories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_farms__farm_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm_id}/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Farm Crops */
        get: operations["list_farm_crops_farms__farm_id__crops_get"];
        put?: never;
        /** Create Farm Crop */
        post: operations["create_farm_crop_farms__farm_id__crops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Farm Timeline */
        get: operations["farm_timeline_farms__farm_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check — no database involved.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Db
         * @description Readiness check — proves the app can actually reach Postgres and
         *     read real data (the crops seeded by migration 0004).
         */
        get: operations["health_db_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Proves the full chain: JWT verified -> role/claims set in Postgres
         *     -> auth.uid() resolves inside the database. jwt_sub and db_auth_uid
         *     must be equal and non-null for RLS to work at all.
         */
        get: operations["whoami_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /**
             * Farm Crop Id
             * Format: uuid
             */
            farm_crop_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Source */
            source: string;
            /** Type */
            type: string;
        };
        /** ActivityCreate */
        ActivityCreate: {
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /**
             * Type
             * @enum {string}
             */
            type: "irrigation" | "fertiliser" | "spray" | "sowing" | "scouting" | "other";
        };
        /**
         * ActivitySummary
         * @description `details` is a JSON string, not a nested object: Groq's strict
         *     schema mode requires every object field to list fixed `properties`
         *     (verified against console.groq.com/docs/structured-outputs,
         *     2026-09-03) -- it does not support an open, arbitrary-key dict like
         *     activities.details actually is (irrigation vs fertiliser vs spray
         *     each have different fields). This field is read-only evidence shown
         *     to the model, never written back, so a JSON string is sufficient and
         *     keeps the schema valid without inventing a fixed shape that doesn't
         *     exist yet.
         */
        ActivitySummary: {
            /** Details */
            details: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Type */
            type: string;
        };
        /**
         * AdvisoryRecord
         * @description A saved answer. `response` is the AdvisoryResponse exactly as it was when
         *     the farmer received it, kept as a plain object on purpose: that contract
         *     grows, and an old row must never fail to load because of a newer schema.
         */
        AdvisoryRecord: {
            /** Abstained */
            abstained: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question */
            question: string;
            /** Response */
            response: {
                [key: string]: unknown;
            };
        };
        /** AdvisoryResponse */
        AdvisoryResponse: {
            /** Abstained */
            abstained: boolean;
            /** Abstained Because */
            abstained_because?: string | null;
            /**
             * Agrochemical Label
             * @default []
             */
            agrochemical_label: components["schemas"]["LabelEntry"][];
            /** Citations Valid */
            citations_valid: boolean;
            /** Confidence */
            confidence?: number | null;
            live_data?: components["schemas"]["WeatherData"] | null;
            /** Model Inference */
            model_inference: string;
            /** Recommendation */
            recommendation: string;
            /**
             * Retrieved Evidence
             * @default []
             */
            retrieved_evidence: components["schemas"]["EvidenceItem"][];
            structured_data: components["schemas"]["FarmContextData"];
            water_balance?: components["schemas"]["WaterBalanceResult"] | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** Crop */
        Crop: {
            /** Default Duration Days */
            default_duration_days: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name En */
            name_en: string;
            /** Name Hi */
            name_hi: string;
        };
        /**
         * EvidenceItem
         * @description One retrieved passage that a VALIDATED citation points at. Every field
         *     except `quote` is copied by code from the chunk/document row.
         */
        EvidenceItem: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Doc Title */
            doc_title: string;
            /** Doc Type */
            doc_type: string;
            /** Licence */
            licence: string;
            /** Page */
            page?: number | null;
            /** Published Year */
            published_year?: number | null;
            /** Quote */
            quote: string;
            /** Source Org */
            source_org: string | null;
            /** Url */
            url: string;
        };
        /** Farm */
        Farm: {
            /** Agro Climatic Zone */
            agro_climatic_zone: string | null;
            /** Area Ha */
            area_ha: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** District */
            district: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Name */
            name: string;
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Soil Texture */
            soil_texture?: ("sandy" | "loamy" | "clayey") | null;
            /** State */
            state: string | null;
        };
        /** FarmContextData */
        FarmContextData: {
            /** Area Ha */
            area_ha?: number | null;
            /** Crop Name */
            crop_name?: string | null;
            /** Days Since Sowing */
            days_since_sowing?: number | null;
            /** Farm Name */
            farm_name: string;
            /**
             * Recent Activities
             * @default []
             */
            recent_activities: components["schemas"]["ActivitySummary"][];
            /** Sowing Date */
            sowing_date?: string | null;
            /** Variety */
            variety?: string | null;
        };
        /** FarmCreate */
        FarmCreate: {
            /** Area Ha */
            area_ha?: number | null;
            /** District */
            district?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Name */
            name: string;
            /** Soil Texture */
            soil_texture?: ("sandy" | "loamy" | "clayey") | null;
            /** State */
            state?: string | null;
        };
        /** FarmCrop */
        FarmCrop: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Crop Id
             * Format: uuid
             */
            crop_id: string;
            /** Expected Harvest */
            expected_harvest: string | null;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sowing Date
             * Format: date
             */
            sowing_date: string;
            /** Status */
            status: string;
            /** Variety */
            variety: string | null;
        };
        /** FarmCropCreate */
        FarmCropCreate: {
            /**
             * Crop Id
             * Format: uuid
             */
            crop_id: string;
            /** Expected Harvest */
            expected_harvest?: string | null;
            /**
             * Sowing Date
             * Format: date
             */
            sowing_date: string;
            /** Variety */
            variety?: string | null;
        };
        /**
         * FarmUpdate
         * @description PATCH body: only the fields sent are changed (`exclude_unset`), and an
         *     explicit null clears a nullable field. Needed because a farm created
         *     without a location or soil type could otherwise never gain one, and the
         *     irrigation water balance (ADR-0015) needs both.
         */
        FarmUpdate: {
            /** Area Ha */
            area_ha?: number | null;
            /** District */
            district?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Name */
            name?: string | null;
            /** Soil Texture */
            soil_texture?: ("sandy" | "loamy" | "clayey") | null;
            /** State */
            state?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LabelEntry
         * @description One label card in the farmer's response. Every field is copied by code
         *     from a verified table row; the model never authors any of it.
         */
        LabelEntry: {
            /** Crop */
            crop: string;
            /** Dilution L Per Ha */
            dilution_l_per_ha?: number | null;
            /** Dose Ai G Per Ha */
            dose_ai_g_per_ha?: number | null;
            /** Dose Formulation */
            dose_formulation: number;
            /**
             * Dose Formulation Unit
             * @enum {string}
             */
            dose_formulation_unit: "g" | "ml";
            /** Formulation */
            formulation: string;
            /**
             * Label Date
             * Format: date
             */
            label_date: string;
            /** Molecule */
            molecule: string;
            /** Pest */
            pest: string;
            /** Row Id */
            row_id: string;
            /** Source Ref */
            source_ref: string;
            /** Table Version */
            table_version: string;
            /** Text */
            text: string;
            /** Waiting Period Days */
            waiting_period_days: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WaterBalanceResult
         * @description What the farmer's response carries as `water_balance`: computed by
         *     code, never written by the model.
         */
        WaterBalanceResult: {
            /** Anchor Date */
            anchor_date?: string | null;
            /** Anchor Kind */
            anchor_kind?: ("sowing" | "logged_irrigation") | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Assumptions
             * @default []
             */
            assumptions: string[];
            /** Crop */
            crop?: string | null;
            /** Data Source */
            data_source?: string | null;
            /** Days Since Sowing */
            days_since_sowing?: number | null;
            /** Days To Raw */
            days_to_raw?: number | null;
            /** Depletion Mm */
            depletion_mm?: number | null;
            /**
             * Forecast Et0 Mm
             * @default []
             */
            forecast_et0_mm: number[];
            /**
             * Forecast Rain Mm
             * @default []
             */
            forecast_rain_mm: number[];
            /** Kc Today */
            kc_today?: number | null;
            /** Last Irrigation On */
            last_irrigation_on?: string | null;
            /** Raw Mm */
            raw_mm?: number | null;
            /** Reason */
            reason?: string | null;
            /** Soil Texture */
            soil_texture?: string | null;
            /** Stage */
            stage?: ("initial" | "development" | "mid" | "late") | null;
            /** Table Version */
            table_version?: string | null;
            /** Taw Mm */
            taw_mm?: number | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "irrigate_now" | "wait" | "cannot_assess";
        };
        /** WeatherData */
        WeatherData: {
            /** Current Rain Mm */
            current_rain_mm?: number | null;
            /** Current Temp C */
            current_temp_c?: number | null;
            /**
             * Forecast Dates
             * @default []
             */
            forecast_dates: string[];
            /**
             * Forecast Rain Mm
             * @default []
             */
            forecast_rain_mm: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_crops_crops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Crop"][];
                };
            };
        };
    };
    create_activity_farm_crops__farm_crop_id__activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_crop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_farms_farms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Farm"][];
                };
            };
        };
    };
    create_farm_farms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Farm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_farm_farms__farm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Farm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_farm_farms__farm_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Farm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_advisories_farms__farm_id__advisories_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisoryRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_farms__farm_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_farm_crops_farms__farm_id__crops_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmCrop"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_farm_crop_farms__farm_id__crops_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmCropCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmCrop"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    farm_timeline_farms__farm_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_db_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    whoami_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
