"""Copy the already-ingested corpus (public.documents + public.chunks) from one database to
another, exactly as it is: same ids, same text, same embeddings.

WHY THIS EXISTS (deployment, 2026-10-05): the 113-chunk corpus and every recorded baseline
(retrieval recall, agent eval, Ragas) were measured on the corpus in the LOCAL database.
Re-running ingest against the remote database would re-parse the PDFs with Docling and could
produce slightly different chunks, which would silently make those baselines describe a different
corpus. Copying keeps remote == the measured corpus.

Reads two URLs from the environment (never on the command line, never printed):
    AGRIAI_SRC_DATABASE_URL   default: the local Supabase stack
    AGRIAI_DST_DATABASE_URL   required (the remote agriai-db connection string)

    python copy_corpus.py            # dry run: prints what it would do, writes nothing
    python copy_corpus.py --apply    # writes, then re-reads the target and compares

chunks.crop_id points at public.crops, whose ids differ per database (they are generated), so
crops are matched by name_en. Only the corpus tables are touched, never farmer data.
"""
import argparse
import asyncio
import hashlib
import os
import sys
from urllib.parse import urlparse

import asyncpg

LOCAL_DEFAULT = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"

DOC_COLS = [
    "id", "source_id", "handle", "title", "publisher", "published_year", "doc_type", "licence",
    "url", "language", "file_sha256", "page_count", "ingested_at", "crops_covered",
]
# `tsv` is generated by the database, so it is not copied; `embedding` travels as text.
CHUNK_COLS = [
    "id", "document_id", "chunk_index", "content", "page_no", "section_path", "language",
    "crop_id", "state", "embedding", "token_count", "created_at",
]


def host_of(url: str) -> str:
    u = urlparse(url)
    return f"{u.hostname}:{u.port}"


def map_crop_ids(src_crops: dict, dst_crops: dict) -> dict:
    """{src crop id: dst crop id}, matched by name. Raises if a name is missing in the target:
    storing NULL or a wrong id would quietly disable the crop filter (ADR-0014)."""
    mapping = {}
    for crop_id, name in src_crops.items():
        match = dst_crops.get(name.lower())
        if match is None:
            raise ValueError(f"crop {name!r} exists in the source but not in the target public.crops")
        mapping[crop_id] = match
    return mapping


def fingerprint(docs: list, chunks: list) -> str:
    """One hash over what matters, order-independent, so source and target can be compared."""
    h = hashlib.sha256()
    for d in sorted(docs, key=lambda r: str(r["id"])):
        h.update(f"{d['id']}|{d['handle']}|{d['file_sha256']}|{d['crops_covered']}".encode())
    for c in sorted(chunks, key=lambda r: str(r["id"])):
        h.update(f"{c['id']}|{c['document_id']}|{c['chunk_index']}|{c['content']}|{c['embedding']}".encode())
    return h.hexdigest()


async def read_corpus(conn: asyncpg.Connection):
    docs = await conn.fetch(f"select {', '.join(DOC_COLS)} from public.documents order by id")
    chunk_sql = ", ".join("embedding::text as embedding" if c == "embedding" else c for c in CHUNK_COLS)
    chunks = await conn.fetch(f"select {chunk_sql} from public.chunks order by id")
    return docs, chunks


async def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="write to the target (default: dry run)")
    args = ap.parse_args()

    src_url = os.environ.get("AGRIAI_SRC_DATABASE_URL", LOCAL_DEFAULT)
    dst_url = os.environ.get("AGRIAI_DST_DATABASE_URL")
    if not dst_url:
        print("Set AGRIAI_DST_DATABASE_URL (the remote connection string) in your shell first.")
        return 2
    if host_of(src_url) == host_of(dst_url):
        print("Source and target are the same host; refusing.")
        return 2

    src = await asyncpg.connect(src_url)
    dst = await asyncpg.connect(dst_url)
    try:
        print(f"source: {host_of(src_url)}   target: {host_of(dst_url)}")
        docs, chunks = await read_corpus(src)
        no_embedding = sum(1 for c in chunks if c["embedding"] is None)
        print(f"source corpus: {len(docs)} documents, {len(chunks)} chunks, {no_embedding} without embedding")
        if not docs or no_embedding:
            print("Nothing to copy, or the source has chunks without embeddings; refusing.")
            return 1

        src_crops = {r["id"]: r["name_en"] for r in await src.fetch("select id, name_en from public.crops")}
        dst_crops = {r["name_en"].lower(): r["id"] for r in await dst.fetch("select id, name_en from public.crops")}
        crop_map = map_crop_ids(src_crops, dst_crops)

        t_docs = await dst.fetchval("select count(*) from public.documents")
        t_chunks = await dst.fetchval("select count(*) from public.chunks")
        t_farms = await dst.fetchval("select count(*) from public.farms")
        print(f"target now: {t_docs} documents, {t_chunks} chunks (and {t_farms} farms, which this script never touches)")

        if not args.apply:
            print("DRY RUN: nothing written. Re-run with --apply to copy.")
            return 0

        handles = [d["handle"] for d in docs]
        async with dst.transaction():
            # Only the documents being copied are replaced (chunks go with them, ON DELETE CASCADE).
            await dst.execute("delete from public.documents where handle = any($1::text[])", handles)
            await dst.executemany(
                f"insert into public.documents ({', '.join(DOC_COLS)}) values "
                f"({', '.join(f'${i}' for i in range(1, len(DOC_COLS) + 1))})",
                [tuple(d[c] for c in DOC_COLS) for d in docs],
            )
            placeholders = ", ".join(
                f"${i}::extensions.vector" if c == "embedding" else f"${i}"
                for i, c in enumerate(CHUNK_COLS, start=1)
            )
            rows = []
            for ch in chunks:
                row = dict(ch)
                row["crop_id"] = crop_map[ch["crop_id"]] if ch["crop_id"] is not None else None
                rows.append(tuple(row[c] for c in CHUNK_COLS))
            await dst.executemany(f"insert into public.chunks ({', '.join(CHUNK_COLS)}) values ({placeholders})", rows)

        # Verify by reading the target back, not by trusting the insert.
        d2, c2 = await read_corpus(dst)
        inv = {v: k for k, v in crop_map.items()}
        c2 = [{**dict(c), "crop_id": inv.get(c["crop_id"])} for c in c2]
        ok = fingerprint(docs, chunks) == fingerprint(d2, c2) and len(d2) == len(docs) and len(c2) == len(chunks)
        print(f"target after: {len(d2)} documents, {len(c2)} chunks; identical to source: {ok}")
        return 0 if ok else 1
    finally:
        await src.close()
        await dst.close()


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
